specVersion: 0.0.1
description: query for starry
repository: https://github.com/poria-cat/starry_query.git
schema: ./schema.graphql
network:
  endpoint: ws://172.17.0.1:9944
  types:
    {
      "TokenType": { "_enum": ["NonFungible", "Fungible"] },
      "CollectionInfo":
        {
          "owner": "AccountId",
          "uri": "Vec<u8>",
          "total_supply": "u128",
          "token_type": "Option<TokenType>",
        },
      "TokenInfo":
        { "end_idx": "u128", "owner": "AccountId", "uri": "Vec<u8>" },
      "DAOInfo":
        {
          "account_id": "AccountId",
          "escrow_id": "AccountId",
          "details": "Vec<u8>",
          "period_duration": "u128",
          "voting_period": "u128",
          "grace_period": "u128",
          "metadata": "Vec<u8>",
          "total_shares": "u128",
          "summoning_time": "BlockNumber",
          "dilution_bound": "u128",
          "proposal_deposit": "Balance",
          "processing_reward": "Balance",
        },
      "Member": { "shares": "u128", "highest_index_yes_vote": "u128" },
    }
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 0
    mapping:
      handlers:
        - handler: handleCollectionCreated
          kind: substrate/CallHandler
          filter:
            module: collectionModule
            method: createCollection
            success: true
        - handler: handleNFTMint
          kind: substrate/EventHandler
          filter:
            module: nftModule
            method: NonFungibleTokenMinted
        - handler: handleFTMint
          kind: substrate/EventHandler
          filter:
            module: nftModule
            method: FungibleTokenMinted
        - handler: handleNFTTransferred
          kind: substrate/EventHandler
          filter:
            module: nftModule
            method: NonFungibleTokenTransferred
        - handler: handleFTTransferred
          kind: substrate/EventHandler
          filter:
            module: nftModule
            method: FungibleTokenTransferred
        - handler: handleNFTBurned
          kind: substrate/EventHandler
          filter:
            module: nftModule
            method: NonFungibleTokenBurned
        - handler: handleFTBurned
          kind: substrate/EventHandler
          filter:
            module: nftModule
            method: FungibleTokenBurned
        - handler: handleSubCreate
          kind: substrate/EventHandler
          filter:
            module: subNftModule
            method: SubCollectionCreated
        - handler: handleSubNFTMint
          kind: substrate/EventHandler
          filter:
            module: subNftModule
            method: SubNonFungibleTokenMinted
        - handler: handleSubFTMint
          kind: substrate/EventHandler
          filter:
            module: subNftModule
            method: SubFungibleTokenMinted
        - handler: handleSubRecover
          kind: substrate/EventHandler
          filter:
            module: subNftModule
            method: TokenRecovered
        - handler: handleSellNFT
          kind: substrate/EventHandler
          filter:
            module: exchangeModule
            method: NonFungibleOrderCreated
        - handler: handleBuyNFT
          kind: substrate/EventHandler
          filter:
            module: exchangeModule
            method: NonFungibleSold
        - handler: handleCancelNFTOrder
          kind: substrate/EventHandler
          filter:
            module: exchangeModule
            method: NonFungibleOrderCanceled
        - handler: handleDAOCreated
          kind: substrate/EventHandler
          filter:
            module: nftdaoModule
            method: DAOCreated
        - handler: handleProposalSubmitted
          kind: substrate/EventHandler
          filter:
            module: nftdaoModule
            method: ProposalSubmitted
        - handler: handleProposalCanceled
          kind: substrate/EventHandler
          filter:
            module: nftdaoModule
            method: ProposalCanceled
        - handler: handleProposalSponsored
          kind: substrate/EventHandler
          filter:
            module: nftdaoModule
            method: ProposalSponsored
        - handler: handleProposalVoted
          kind: substrate/EventHandler
          filter:
            module: nftdaoModule
            method: ProposalVoted
        - handler: handleProposalExecuted
          kind: substrate/EventHandler
          filter:
            module: nftdaoModule
            method: ProposalExecuted
        - handler: handleProposalProcessed
          kind: substrate/EventHandler
          filter:
            module: nftdaoModule
            method: ProposalProcessed
        - handler: handleMemberRagequited
          kind: substrate/EventHandler
          filter:
            module: nftdaoModule
            method: MemberRagequited
        - handler: handleNonFungibleTokenLinked
          kind: substrate/EventHandler
          filter:
            module: graphModule
            method: NonFungibleTokenLinked
        - handler: handleNonFungibleTokenRecovered
          kind: substrate/EventHandler
          filter:
            module: graphModule
            method: NonFungibleTokenRecovered
